with Ada.Text_IO;           use Ada.Text_IO;
with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;
with GNATCOLL.JSON;         use GNATCOLL.JSON;
with Ada.Containers.Vectors;

procedure Loom_Mittens_Parser is

   -- Define a record to hold the config
   type Contributor_Config is record
      Name        : Unbounded_String;
      Role        : Unbounded_String;
      Sandbox     : Unbounded_String;
      Care_Mode   : Boolean;
      Badge_Goals : Unbounded_String;
      Salt_States : Unbounded_String;
      -- Shells and Grains omitted for brevity in this parser
   end record;

   package Config_Vector is new Ada.Containers.Vectors
     (Index_Type => Natural, Element_Type => Contributor_Config);

   -- This procedure replaces the hard-coded stub function
   procedure Parse_JSON_Config (Path : String; Configs : out Config_Vector.Vector) is
      Tree    : JSON_Value;
      Root    : JSON_Object;
      Contrib_Array : JSON_Array;
   begin
      Tree := Read (Path);
      Root := Get (Tree);
      Contrib_Array := Get (Root, "contributors");

      for Elem of Contrib_Array loop
         declare
            Config_Obj : JSON_Object := Get(Elem);
            Temp_Rec   : Contributor_Config;
            Goals_Array : JSON_Array := Get(Config_Obj, "badge_goals");
            Goals_Str   : Unbounded_String;
         begin
            -- Build the badge goals string
            for Goal of Goals_Array loop
               Append (Goals_Str, Get_String(Goal) & " ");
            end loop;

            Temp_Rec.Name        := To_Unbounded_String(Get_String(Config_Obj, "name"));
            Temp_Rec.Role        := To_Unbounded_String(Get_String(Config_Obj, "role"));
            Temp_Rec.Sandbox     := To_Unbounded_String(Get_String(Config_Obj, "sandbox"));
            Temp_Rec.Care_Mode   := Get_Boolean(Config_Obj, "care_mode");
            Temp_Rec.Badge_Goals := Goals_Str;
            -- Salt_States parsing omitted for brevity

            Configs.Append (Temp_Rec);
         end;
      end loop;

   exception
      when others =>
         Put_Line (Standard_Error, "Error: Failed to parse intermediate config file.");
         raise;
   end Parse_JSON_Config;

   -- Emit_SLS, Emit_Init, and Emit_Profile now take dynamic data
   procedure Emit_SLS (Config : Contributor_Config) is
     F : File_Type;
     Path : String := "config/salt/contributor/" & To_String (Config.Name) & ".sls";
   begin
     Create (F, Out_File, Path);
     Put_Line (F, "install_git:\n  pkg.installed:\n    - name: git");
     Put_Line (F, "configure_user:\n  user.present:\n    - name: " & To_String (Config.Role));
     -- Simplified for this example
     Close (F);
   end Emit_SLS;

   procedure Emit_Init (Config : Contributor_Config) is
     -- This now reads from the parsed config, not a hardcoded list
     -- For this example, we just emit one for 'sh'
     F : File_Type;
     Path : String := "loom-init.sh";
   begin
     Create (F, Out_File, Path);
     Put_Line (F, "# --- Emitted by Loom_Mittens_Parser ---");
     Put_Line (F, "export LOOM_ROLE=""" & To_String (Config.Role) & """");
     Put_Line (F, "export LOOM_CARE_MODE=""" & Config.Care_Mode'Img & """");
     Put_Line (F, "export LOOM_SANDBOX=""" & To_String (Config.Sandbox) & """");
     Put_Line (F, "export LOOM_BADGES=""" & To_String (Config.Badge_Goals) & """");
     Close (F);
   end Emit_Init;
   
   procedure Emit_Profile (Config : Contributor_Config) is
     F : File_Type;
     Path : String := "docs/contributors/" & To_String (Config.Name) & ".adoc";
   begin
     Create (F, Out_File, Path);
     Put_Line (F, "= Contributor Profile: " & To_String (Config.Name));
     -- ... etc ...
     Close (F);
   end Emit_Profile;


   All_Configs : Config_Vector.Vector;
   Config_Path : constant String := "loom.mittens.intermediate.json";

begin
   -- 1. Parse the JSON file generated by Nickel
   Parse_JSON_Config (Config_Path, All_Configs);

   -- 2. Iterate and emit files for each contributor
   Put_Line ("INFO: Found " & All_Configs.Length'Img & " contributors to process.");
   for Config of All_Configs loop
      Put_Line ("INFO: Emitting artifacts for " & To_String(Config.Name));
      Emit_SLS (Config);
      Emit_Init (Config);
      Emit_Profile (Config);
   end loop;

end Loom_Mittens_Parser;
